site_name: Graphemy
repo_url: https://github.com/MDoreto/graphemy
repo_name: MDoreto/graphemy
edit_uri: tree/master/docs


markdown_extensions:
- attr_list
- mdx_include
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
- pymdownx.blocks.admonition:
    types:
    - note
    - info
    - tip
    - warning
    - danger
- pymdownx.tabbed:
    alternate_style: true
    

extra_css:
  - stylesheets/extra.css

plugins:
- macros
- search
- mkdocstrings:
    handlers:
      python: 
        paths: [graphemy]

extra:
  commands:
    run: poetry run graphemy
