[tool.poetry]
name = "graphemy"
version = "0.1.0"
description = ""
authors = ["Matheus Doreto <matheus.alencar@prometeon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlmodel = "^0.0.11"
strawberry-graphql = {extras = ["debug-server"], version = "^0.211.1"}
fastapi = "^0.104.1"
python-dotenv = "^1.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
blue = "^0.9.1"
isort = "^5.12.0"
taskipy = "^1.12.0"
pytest-asyncio = "^0.21.1"
httpx = "^0.25.0"
pytest-env = "^1.1.1"


[tool.poetry.group.doc.dependencies]
mkdocs-material = "^9.4.7"
mkdocstrings = "^0.23.0"
mkdocstrings-python = "^1.7.3"
mkdocs-macros-plugin = "^1.0.5"
jinja2 = "^3.1.2"
mdx-include = "^1.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"


[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "blue . && isort ."
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -s -x --cov=graphemy -vv -W ignore::DeprecationWarning"
post_test = "coverage html"