name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name:  Copy files
        uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install uv
      
      - name: Install dependencies
        run: poetry install --no-group doc
      
      - name: Run tests
        run: uv run task test --cov-report=xml
      
      - name: Upload coverage reports to Codecov
        uses:  codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN }}
